# Generated by Django 5.2.12 on 2026-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstaff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('receptionist', 'Receptionist'), ('waiter', 'Waiter'), ('waitress', 'Waitress')], max_length=20),
        ),
    ]
