# Generated by Django 5.2.12 on 2026-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramotp',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramotp',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='telegramotp',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
