# Generated by Django 5.2.12 on 2026-04-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramotp_attempt_count_telegramotp_max_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramotp',
            options={'ordering': ['-id']},
        ),
    ]
