# Generated by Django 5.2.12 on 2026-05-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_telegramotp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('owner', 'Owner'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('superadmin', 'Superadmin')], default='consumer', max_length=20),
        ),
    ]
