# Generated by Django 5.2.12 on 2026-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('owner', 'Owner'), ('superadmin', 'Superadmin')], default='consumer', max_length=20),
        ),
    ]
