# Generated by Django 5.2.12 on 2026-05-31 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_branchstaff'),
        ('restaurants', '0002_branch_booking_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchstaff',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='branchstaff',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='branchstaff',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='restaurants.branch'),
        ),
        migrations.AlterField(
            model_name='branchstaff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('receptionist', 'Receptionist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='branchstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('owner', 'Owner'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('superadmin', 'Superadmin')], default='consumer', max_length=20),
        ),
    ]
