# Generated by Django 5.2.12 on 2026-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_branchstaff_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreationaudit',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='usercreationaudit',
            name='creator',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('owner', 'Owner'), ('superadmin', 'Superadmin')], default='consumer', max_length=20),
        ),
        migrations.DeleteModel(
            name='BranchStaff',
        ),
        migrations.DeleteModel(
            name='UserCreationAudit',
        ),
    ]
