# Generated by Django 5.2.12 on 2026-05-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_usercreationaudit_created_user_and_more'),
        ('restaurants', '0002_branch_booking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='restaurants.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('owner', 'Owner'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('superadmin', 'Superadmin')], default='consumer', max_length=20),
        ),
    ]
