@baseUrl = http://127.0.0.1:8000/api/accounts
@consumer_token = consumer_login_dan_olingan_token
@owner_token = owner_login_dan_olingan_token
@manager_token = manager_login_dan_olingan_token
@receptionist_token = receptionist_login_dan_olingan_token
@partner_token = partner_login_dan_olingan_token
@superadmin_token = superadmin_login_dan_olingan_token


@baseUrl = http://127.0.0.1:8000/api/accounts

### ===========================
### CONSUMER
### ===========================
POST {{baseUrl}}/consumer/request-register-otp/
Content-Type: application/json
{"phone": "998901234567"}

POST {{baseUrl}}/consumer/register/
Content-Type: application/json
{
  "phone": "998901234567",
  "code": "123456",
  "first_name": "John",
  "last_name": "Doe",
  "password": "pass123",
  "password_repeat": "pass123"
}

POST {{baseUrl}}/consumer/login/
Content-Type: application/json
{
  "phone": "998901234567",
  "password": "pass123"
}

POST {{baseUrl}}/consumer/forgot-password/request/
Content-Type: application/json
{"phone": "998901234567"}

POST {{baseUrl}}/consumer/forgot-password/confirm/
Content-Type: application/json
{
  "phone": "998901234567",
  "code": "654321",
  "new_password": "newpass123",
  "new_password_repeat": "newpass123"
}


### ===========================
### OWNER
### ===========================
POST {{baseUrl}}/owner/register/
Content-Type: application/json
{
  "email": "owner@resto.com",
  "first_name": "Restaurant",
  "last_name": "Owner",
  "password": "owner123",
  "password_repeat": "owner123"
}

POST {{baseUrl}}/owner/login/
Content-Type: application/json
{
  "email": "owner@resto.com",
  "password": "owner123"
}

POST {{baseUrl}}/owner/forgot-password/request/
Content-Type: application/json
{"email": "owner@resto.com"}

POST {{baseUrl}}/owner/forgot-password/confirm/
Content-Type: application/json
{
  "email": "owner@resto.com",
  "code": "123456",
  "new_password": "newowner123",
  "new_password_repeat": "newowner123"
}


### ===========================
### MANAGER / RECEPTIONIST
### ===========================
POST {{baseUrl}}/staff/register/
Content-Type: application/json
{
  "email": "manager@resto.com",
  "first_name": "Jane",
  "last_name": "Manager",
  "role": "manager",
  "branch_id": 1,
  "password": "staff123",
  "password_repeat": "staff123"
}

POST {{baseUrl}}/staff/login/
Content-Type: application/json
{
  "email": "manager@resto.com",
  "password": "staff123"
}

POST {{baseUrl}}/staff/forgot-password/request/
Content-Type: application/json
{"email": "manager@resto.com"}

POST {{baseUrl}}/staff/forgot-password/confirm/
Content-Type: application/json
{
  "email": "manager@resto.com",
  "code": "123456",
  "new_password": "newstaff123",
  "new_password_repeat": "newstaff123"
}


### ===========================
### PROFILE
### ===========================
GET {{baseUrl}}/me/
Authorization: Bearer {{receptionist_token}}

PATCH {{baseUrl}}/me/
Authorization: Bearer {{receptionist_token}}
Content-Type: application/json
{
  "bio": "I love working here!"
}


### ===========================
### SUPERADMIN CREATE OWNER
### ===========================
POST {{baseUrl}}/create-owner/
Authorization: Bearer {{superadmin_token}}
Content-Type: application/json
{
  "email": "newowner@example.com",
  "password": "ownerpass123"
}