@baseUrl = http://127.0.0.1:8000/api/restaurants
@ownerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3ODAwMDk4LCJpYXQiOjE3Nzc3OTk3OTgsImp0aSI6ImM5NzViMTM3MmEzZDQ3OTE5MDk1YWQzNGRlNzVhMGY1IiwidXNlcl9pZCI6IjIifQ.r-4VjUMbZgGxIWPEfBYac1e-oiPjAjI1V1g7AwSP8iY
@superToken = YOUR_SUPERADMIN_ACCESS_TOKEN

### Public branches list
GET {{baseUrl}}/branches/

### Public branch detail
GET {{baseUrl}}/branches/1/

### Partner brand list
GET {{baseUrl}}/partner/brands/
Authorization: Bearer {{ownerToken}}

### Partner create brand
POST {{baseUrl}}/partner/brands/create/
Authorization: Bearer {{ownerToken}}
Content-Type: application/json

{
  "name": "OLDINDAN Bistro",
  "slug": "oldindan-bistro",
  "description": "Main restaurant brand"
}

### Partner branch list
GET {{baseUrl}}/partner/branches/
Authorization: Bearer {{ownerToken}}

### Partner create branch
POST {{baseUrl}}/partner/branches/create/
Authorization: Bearer {{ownerToken}}
Content-Type: application/json

{
  "brand": 1,
  "name": "Kfc Almazor",
  "slug": "kfc-almazor",
  "address": "Almazor, Tashkent",
  "latitude": 41.275,
  "longitude": 69.203,
  "phone": "998901112233",
  "is_active": true,
  "service_fee": 5000,
  "deposit_enabled": false,
  "deposit_amount": 0,
  "working_hours": {
    "mon": ["09:00", "23:00"],
    "tue": ["09:00", "23:00"],
    "wed": ["09:00", "23:00"],
    "thu": ["09:00", "23:00"],
    "fri": ["09:00", "23:00"],
    "sat": ["10:00", "00:00"],
    "sun": ["10:00", "22:00"]
  },
  "booking_hours": {
    "mon": ["10:00", "22:30"],
    "tue": ["10:00", "22:30"],
    "wed": ["10:00", "22:30"],
    "thu": ["10:00", "22:30"],
    "fri": ["10:00", "23:00"],
    "sat": ["11:00", "23:30"],
    "sun": ["11:00", "21:30"]
  }
}

### Partner branch detail
GET {{baseUrl}}/partner/branches/1/
Authorization: Bearer {{ownerToken}}

### Partner branch update
PATCH {{baseUrl}}/partner/branches/1/
Authorization: Bearer {{ownerToken}}
Content-Type: application/json

{
  "service_fee": 7000,
  "deposit_enabled": true,
  "deposit_amount": 30000
}