# Generated by Django 5.2.12 on 2026-05-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_created', 'Bron yaratildi'), ('booking_canceled', 'Bron bekor qilindi'), ('booking_confirmed', 'Bron tasdiqlandi'), ('booking_updated', 'Bron yangilandi'), ('system', 'Tizim xabari')], max_length=50),
        ),
    ]
