# Generated by Django 5.2.12 on 2026-05-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_created', 'Bron yaratildi'), ('booking_canceled', 'Bron bekor qilindi'), ('booking_confirmed', 'Bron tasdiqlandi'), ('booking_updated', 'Bron yangilandi'), ('booking_checked_in', 'Bron faollashtirildi'), ('booking_completed', 'Bron yakunlandi'), ('booking_no_show', 'Kelmagan'), ('system', 'Tizim xabari')], max_length=50),
        ),
    ]
